### ISSUE TITLE
Onsite Payments

### ISSUE THREAD

**Issue by brytey2k** [DreamOval/slydepay-php-connector#1]
Please can there be or is there a feature that allows payment in my web application without the user leaving my site?

**Comment by Tech-Emiretus** [comment]
Yeah I really need this feature too

**Comment by kdjomeda** [comment]
Sorry for the late revert. I will pass on this to the product team and get back to you guys. Thanks for using this.

**Comment by kdjomeda** [comment]
Feature not available upstream
