### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by webncrafts** [DreamOval/slydepay-php-connector#12]
Response : stdClass Object ( [ProcessPaymentOrderResult] => Error: 1 )

Debug::
Slydepay\Exception\InvalidPayTokenException: Return token is not a valid GUID ::Error: 1:: is returned instead in /home/aju/Slydepay/vendor/slydepay/slydepay-soap/src/Slydepay.php:63 Stack trace: #0 /home/aju/Slydepay/index.php(36): Slydepay\Slydepay->processPaymentOrder(Object(Slydepay\Order\Order)) #1 {main}

**Comment by dovalltd** [comment]
Hi DreamOval/slydepay-php-connector!

Thank you for your message. Our team will reply to you very shortly
and we'll update you by email.

You can log in and view your entire conversation history with us at
anytime in our Help Center
[https://support.dreamoval.com/conversation/view/45664].

Thank you! 

This is a Dreamoval Limited message delivered by Kayako
[https://kayako.com].

**Comment by webncrafts** [comment]
First can you please help me signup as a Business Account

![image](https://user-images.githubusercontent.com/48272537/58474125-f85d7600-8167-11e9-9550-647abf90d7ca.png)

**Comment by webncrafts** [comment]
I am calling Order::create();

**Comment by dovalltd** [comment]
How did we do?
Wed love to hear what you think about our service.
[img
src="https://dreamoval.kayakocdn.com/__apps/cases/assets/__universal/images/email/face-happy.png"
width="42" height="42" alt="Good, Im satisfied."]
Good, Im satisfied.
[https://support.dreamoval.com/conversation/rating/45664/c7a43d4c02f8987db14fe00adfd6e0dbf76e9697/3523409790/GOOD]
[img
src="https://dreamoval.kayakocdn.com/__apps/cases/assets/__universal/images/email/face-sad.png"
width="42" height="42" alt="Bad, I am not satisfied"]
Bad, I am not satisfied
[https://support.dreamoval.com/conversation/rating/45664/c7a43d4c02f8987db14fe00adfd6e0dbf76e9697/3523409790/BAD]


 This is a Dreamoval Limited message delivered by Kayako
[https://kayako.com].

**Comment by Samrob90** [comment]
i am using the  api in my website and i keep getting this error:

Return token is not a valid GUID ::Error: 3:: is returned instead in C:\wamp64\www\books\vendor\slydepay\slydepay-soap\src\Slydepay.php:63 Stack trace: #0 C:\wamp64\www\books\public\php\main.php(80): Slydepay\Slydepay->processPaymentOrder(Object(Slydepay\Order\Order)) #1 {main}

**Comment by dovalltd** [comment]
Hi DreamOval/slydepay-php-connector!

Thank you for your message. Our team will reply to you very shortly
and we'll update you by email.

You can log in and view your entire conversation history with us at
anytime in our Help Center
[https://support.dreamoval.com/conversation/view/46950].

Thank you! 

This is a Dreamoval Limited message delivered by Kayako
[https://kayako.com].

**Comment by dovalltd** [comment]
How did we do?
Wed love to hear what you think about our service.
[img
src="https://dreamoval.kayakocdn.com/__apps/cases/assets/__universal/images/email/face-happy.png"
width="42" height="42" alt="Good, Im satisfied."]
Good, Im satisfied.
[https://support.dreamoval.com/conversation/rating/46950/e94159a63acf9418f266237337c92a1821f17912/1663017686/GOOD]
[img
src="https://dreamoval.kayakocdn.com/__apps/cases/assets/__universal/images/email/face-sad.png"
width="42" height="42" alt="Bad, I am not satisfied"]
Bad, I am not satisfied
[https://support.dreamoval.com/conversation/rating/46950/e94159a63acf9418f266237337c92a1821f17912/1663017686/BAD]


 This is a Dreamoval Limited message delivered by Kayako
[https://kayako.com].

**Comment by kdjomeda** [comment]
Both error 1 and 3 means Merchant credentials invalid , and merchant not verified as explained here https://s3.amazonaws.com/slydepay-public/docs/SlydepayMerchantApi_V_1.4.pdf and here https://github.com/DreamOval/slydepay-php-connector/issues/14#issuecomment-826667524
