### ISSUE TITLE
Return token is not a valid GUID

### ISSUE THREAD

**Issue by amitkumar86877** [DreamOval/slydepay-php-connector#13]
> Hello,
> slydepay Working fine on API Integration Mode but after un-check the API integration mode this is giving error like flowing. if anyone knows how to solve this issue please help us.

exception 'Slydepay\Exception\InvalidPayTokenException' with message 'Return token is not a valid GUID ::Error: 3:: is returned instead' in /opt/lampp/htdocs/weofthing/vendor/slydepay/slydepay-soap/src/Slydepay.php:66 Stack trace: #0 /opt/lampp/htdocs/weofthing/src/Controller/WebservicesController.php(2850): Slydepay\Slydepay->processPaymentOrder(Object(Slydepay\Order\Order)) #1 /opt/lampp/htdocs/weofthing/vendor/cakephp/cakephp/src/Controller/Controller.php(440): App\Controller\WebservicesController->paymentsUsingSlydePay() #2 /opt/lampp/htdocs/weofthing/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction() #3 /opt/lampp/htdocs/weofthing/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\WebservicesController)) #4 /opt/lampp/htdocs/weofthing/vendor/cakephp/cakephp/src/Http/BaseApplication.php(108): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #5 /opt/lampp/htdocs/weofthing/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner)) #6 /opt/lampp/htdocs/weofthing/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(104): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #7 /opt/lampp/htdocs/weofthing/vendor/cakephp/cakephp/src/Http/Runner.php(65): 
Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner)) #8 /opt/lampp/htdocs/weofthing/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #9 /opt/lampp/htdocs/weofthing/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner)) #10 /opt/lampp/htdocs/weofthing/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #11 /opt/lampp/htdocs/weofthing/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner)) #12 /opt/lampp/htdocs/weofthing/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #13 /opt/lampp/htdocs/weofthing/vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner)) #14 /opt/lampp/htdocs/weofthing/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #15 /opt/lampp/htdocs/weofthing/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #16 /opt/lampp/htdocs/weofthing/webroot/index.php(40): Cake\Http\Server->run() #17 {main}

**Comment by dovalltd** [comment]
Hi DreamOval/slydepay-php-connector!

Thank you for your message. Our team will reply to you very shortly
and we'll update you by email.

You can log in and view your entire conversation history with us at
anytime in our Help Center
[https://support.dreamoval.com/conversation/view/127506].

Thank you! 

This is a Dreamoval Limited message delivered by Kayako
[https://kayako.com].

**Comment by instincts88** [comment]
I have the same issue but i cannot access the entire conversation history

**Comment by kdjomeda** [comment]
https://github.com/DreamOval/slydepay-php-connector/issues/14#issuecomment-826667524 @amitkumar86877 this link has your answer.
