### ISSUE TITLE
Return token is not a valid GUID

### ISSUE THREAD

**Issue by instincts88** [DreamOval/slydepay-php-connector#14]
Hello,
slydepay Working fine on API Integration Mode but after un-check the API integration mode this is giving error like flowing. if anyone knows how to solve this issue please help us

Type: Slydepay\Exception\ProcessPaymentException
Message: Slydepay\Exception\InvalidPayTokenException: Return token is not a valid GUID ::Error: 3:: is returned instead in C:\xampp\htdocs\api\vendor\slydepay\slydepay-soap\src\Slydepay.php:63 Stack trace: #0 C:\xampp\htdocs\api\test.php(47): Slydepay\Slydepay->processPaymentOrder(Object(Slydepay\Order\Order)) #1 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Array) #2 C:\xampp\htdocs\api\vendor\slim\slim\Slim\Handlers\Strategies\RequestResponse.php(40): call_user_func(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array) #3 C:\xampp\htdocs\api\vendor\slim\slim\Slim\Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array) #4 C:\xampp\htdocs\api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response)) #5 C:\xampp\htdocs\api\vendor\slim\slim\Slim\Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response)) #6 C:\xampp\htdocs\api\vendor\slim\slim\Slim\App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response)) #7 C:\xampp\htdocs\api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response)) #8 C:\xampp\htdocs\api\vendor\slim\slim\Slim\App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response)) #9 C:\xampp\htdocs\api\vendor\slim\slim\Slim\App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response)) #10 C:\xampp\htdocs\api\test.php(68): Slim\App->run() #11 {main}
File: C:\xampp\htdocs\api\vendor\slydepay\slydepay-soap\src\Slydepay.php
Line: 68

**Comment by kdjomeda** [comment]
Hello you are getting an Error: 3 which means "Merchant Account Not Verify". https://s3.amazonaws.com/slydepay-public/docs/SlydepayMerchantApi_V_1.4.pdf on page 9 . You were to get verified according to BoG regulation before you can go live, ie accepting real money. When you uncheck integration mode, you saying you are in production and accepting real money.  
I hope this helps

**Comment by kdjomeda** [comment]
Kindly reach out of support to get your account validated/verified.
