### ISSUE TITLE
FatalThrowableError in Slydepay.php line 153: Class 'SoapClient' not found

### ISSUE THREAD

**Issue by MaggicBones** [DreamOval/slydepay-php-connector#5]
I get this error when I try to use your SDK with Laravel 5.4

**Comment by MaggicBones** [comment]
Sorry, I had to turn SOAP dll in php.ini

**Comment by kdjomeda** [comment]
I think this means it's closed then. Happy Coding

**Comment by MaggicBones** [comment]
Thanks!
