### ISSUE TITLE
Failed on Heroku

### ISSUE THREAD

**Issue by ovvval** [DreamOval/slydepay-php-connector#7]
I have tested the sample code in my app hosted on heroku but I keep getting errors

**Comment by ovvval** [comment]
I keep getting this error anytime I use version of the API.

Fatal error: Uncaught Error: Class '**SoapClient**' not found in C:\xampp\htdocs\projectdirectory\slydepay\Integrator.class.php:28 Stack trace: #0 C:\xampp\htdocs\projectdirectory\dashboard\ajax\branches\payslydepay.php(71): SlydepayConnector->__construct('http://www.i-wa...', 'https://app.sly...', 1.4, 'myemail@gmail...', 'myemail@gmail...', 'C2B', true) #1 {main} thrown in C:\xampp\htdocs\projectdirectory\slydepay\Integrator.class.php on line 28

> NB: I have changed the values of sensitive data in the error for security reasons.

Please a quick response or guide will be highly appreciated.

Thanks

**Comment by kdjomeda** [comment]
Hello @ovvval I think this is pretty much and environment issue. SoapClient is a php native library. I think your error file is telling you that it doesn't exist in your environment. Have you done due diligence in finding out if you have soap installed to start with?

**Comment by ovvval** [comment]
Hello @kdjomeda 
I did a little digging and with the help of this article, https://stackoverflow.com/questions/2509143/php-how-do-i-install-soap-extension I edited the php.ini file to activate the extension. Yet I get the same results on localhost.

I pushed my code and it fails on heroku too.

**Comment by ovvval** [comment]
It works now. I contacted Heroku and had the soap extension enabled.

Thank @kdjomeda for your help
