### ISSUE TITLE
Error in running the app

### ISSUE THREAD

**Issue by 1988gadocansey** [DreamOval/slydepay-php-connector#8]
Fatal error: Uncaught Slydepay\Exception\ProcessPaymentException: SoapFault exception: [soap:Server] Index: 0, Size: 0 in /Applications/XAMPP/xamppfiles/htdocs/slydePay/vendor/slydepay/slydepay-soap/src/Slydepay.php:61 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/slydePay/vendor/slydepay/slydepay-soap/src/Slydepay.php(61): SoapClient->__call('ProcessPaymentO...', Array) #1 /Applications/XAMPP/xamppfiles/htdocs/slydePay/index.php(39): Slydepay\Slydepay->processPaymentOrder(Object(Slydepay\Order\Order)) #2 {main} in /Applications/XAMPP/xamppfiles/htdocs/slydePay/vendor/slydepay/slydepay-soap/src/Slydepay.php:68 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/slydePay/index.php(39): Slydepay\Slydepay->processPaymentOrder(Object(Slydepay\Order\Order)) #1 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/slydePay/vendor/slydepay/slydepay-soap/src/Slydepay.php on line 68

**Comment by dagasonhackason** [comment]
@1988gadocansey i know the fix its simple u made a mistake where the items array comes u forgot to make it an array. example most people forget the [ ] before the { } so instead of items: [ { "id" : "", "name" : "", "price" : "", "quantity" : 1}] and do this rather items: { "id" : "", "name" : "", "price" : "", "quantity" : 1 } without the [ ] but that part takes an array so it wont work make sure make it an array even if u are using xml u see its telling u theres a problem with your array....

**Comment by dagasonhackason** [comment]
@anupamverma932 your problem is u are sending the same order id again after u used it to receive a token make sure its always unique try doing that check always at ur end before u send orderid out with the other info to the Slydepay class.

**Comment by ash11nb22** [comment]
```
try {
    // Make request to Slydepay and get the response object for the redirect url
    $response = $slydepay->processPaymentOrder($order);
    return $response->redirectUrl();
} catch (Slydepay\Exception\ProcessPayment $e) {
    echo $e->getMessage();
}
```
pay_token URL will be generated from this and just want to view the generated URL but am getting error  
**"Call to a member function redirectUrl() on array"**
the error is coming from this line `return $response->redirectUrl();`
_Am using laravel._

**Comment by kdjomeda** [comment]
https://github.com/DreamOval/slydepay-php-connector/issues/14#issuecomment-826667524
